package Timer.timer_use_cases;

import Timer.timer_entity.TimerEntity;

import java.util.Timer;
import java.util.TimerTask;

/**
 * Use case class for the timer.
 */
public class TimerInteractor implements TimerInputBoundary {

    /**
     * The inputs that will be processed by the interactor.
     */
    final TimerRequestModel timerRequestModel;
    /**
     * The outputs that will be generated by the interactor.
     */
    final TimerResponseModel timerResponseModel;
    /**
     * The Entity class for the timer.
     */
    TimerEntity timerEntity = new TimerEntity();
    Timer timer = new Timer();

    /**
     * Constructor for the TimerInteractor class.
     * @param timerRequestModel the inputs that will be processed by the interactor
     * @param timerResponseModel the outputs that will be generated by the interactor
     */
    public TimerInteractor(TimerRequestModel timerRequestModel, TimerResponseModel timerResponseModel) {
        this.timerRequestModel = timerRequestModel;
        this.timerResponseModel = timerResponseModel;
    }

    /**
     * Starts the timer of timerEntity by creating a new instance of it and using its startTimer method. If the custom
     * time is the default value of -1, the preset time will be used. If not, the custom time will be used.
     */
    @Override
    public void startTimer() {
        timerEntity = new TimerEntity();
        if (timerRequestModel.getCustomTime().equals("-1")) {
            timerEntity.setTimer(convertTimeToArray(timerRequestModel.getSelectedTime()));
        }
        else {
            timerEntity.setTimer(convertTimeToArray(timerRequestModel.getCustomTime()));
        }
        timerEntity.startTimer();
        timer = new Timer();
        timer.scheduleAtFixedRate(new TimerTask() {
            @Override
            public void run() {
                timerResponseModel.setOutputTime(timerEntity.timeLeft);
            }
        }, 0, 100);
    }

    /**
     * Ends the timer of timerEntity using its endTimer method. The elapsed time is updated and timerEntity is deleted.
     */
    @Override
    public void endTimer() {
        timer.cancel();
        timer.purge();
        timerEntity.endTimer();
        timerResponseModel.setElapsedTime(timerResponseModel.getElapsedTime() + timerEntity.getElapsedTime());
        timerEntity = null;
    }

    /**
     * Sets the starting time of timerEntity using its setTimer method.
     * @param time the starting time
     */
    @Override
    public void setTimer(int[] time) {
        timerEntity.setTimer(time);
    }

    /**
     * Converts String time into an int array containing the hours, minutes and seconds of time.
     * @param time the time with format (00:00:00)
     * @return the input time in hours, minutes, seconds
     */
    private int[] convertTimeToArray(String time) {
        int[] convertedTime = new int[3];
        String[] times = time.split(":", 3);
        convertedTime[0] = Integer.parseInt(times[0]);
        convertedTime[1] = Integer.parseInt(times[1]);
        convertedTime[2] = Integer.parseInt(times[2]);
        return convertedTime;
    }
}
